### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by duramato** [mgrachev/gastly#3]
Ive just installed gastly via ruby gems, and tried runnning but i just got this 

```
# Gastly.capture('http://google.com', 'output.png')
-bash: syntax error near unexpected token `'http://google.com','
```

**Comment by mgrachev** [comment]
@duramato You must first run `irb` and it run this example:

```
$ gem install gastly
$ irb
irb(main):001:0> require 'gastly'
=> true
irb(main):002:0> Gastly.capture('http://google.com', 'output.png')
=> "output.png"
```

Or without `irb`:

```
$ ruby -e "require 'gastly'; Gastly.capture('http://google.com', 'output.png')"
```

**Comment by duramato** [comment]
Oh ok , i was thinking it was a stand alone package.
And i tried the one liner example with google and it seemed to work, but then i tried with another [page](http://applemusic.tumblr.com/beats1) and it only worked "partially". http://img.cla46.com/up/146815992883d84c0.png

**Comment by mgrachev** [comment]
@duramato There are problems with the display of this website in [PhantomJS](http://phantomjs.org), i can not do anything about it.
