### ISSUE TITLE
Syntax error, unexpected tPOW

### ISSUE THREAD

**Issue by rehrumesh** [mgrachev/gastly#4]
![image](https://cloud.githubusercontent.com/assets/2035004/17550408/75e79158-5f12-11e6-97cc-82ae439b9fea.png)

Hi I am trying to use gastly and getting abouve error. Any ideas why and how to fix it?

**Comment by mgrachev** [comment]
@rehrumesh Hi. You need to use Ruby version is 2.1.0 or higher.

**Comment by rehrumesh** [comment]
Oh Thanks for the quick response. :+1:
