### ISSUE TITLE
Not working with dynamic urls

### ISSUE THREAD

**Issue by KranthiKishore** [mgrachev/gastly#5]
Hi,

I'm trying to generate an image  from a dynamic url which comes in parameters
`Parameters: {"share_url"=>"http://localhost:3000//share?id=Ym1jLTk0"}`
and in my code am doing `Gastly.capture(params[:share_url], "destination.png")`

But its taking lot of time. When I try the same in rails console, its generating image in couple of seconds.

Could you please tell me the solution?

**Comment by mgrachev** [comment]
Hi, @KranthiKishore. You use WEBrick as an application server?

**Comment by KranthiKishore** [comment]
@mgrachev  Yes.

**Comment by mgrachev** [comment]
@KranthiKishore You need to use the multi-threaded server, such as a [Puma](https://github.com/puma/puma).

**Comment by KranthiKishore** [comment]
@mgrachev  you mean I have to start puma server with multiple threads? Because I used puma gem but that too doesn't work

**Comment by mgrachev** [comment]
@KranthiKishore What server starts with the command `rails server`?

To start the Puma server, run the command: `bundle exec rails s puma`

**Comment by KranthiKishore** [comment]
@mgrachev I have tried the same but its taking longer time to generate images. Infact not generating.

**Comment by KranthiKishore** [comment]
my controller code looks like

```
def download
  screeenshot = Gastly.capture(params[:share_url], 'test.png')
end
```

But don't see any image(test.png) generated in rails root directory. Can you tell me what might be the problem?

**Comment by mgrachev** [comment]
@KranthiKishore I created a test project on Ruby on Rails 4.2.7 - https://github.com/mgrachev/gastly_test_project. Everything works, screenshots generated.

**Comment by stalin** [comment]
@KranthiKishore If app is running on dev environment and your share_url points to the same server, you need to enable the concurrency by setting `config.allow_concurrency = true`

**Comment by KranthiKishore** [comment]
Thanks @stalin it worked :+1:  :smile:
