### ISSUE TITLE
Style Sheet not work and need option to take only visible screen's screenshot

### ISSUE THREAD

**Issue by ronakpatel70** [mgrachev/gastly#7]
Hi,

i am trying to capture a screenshot from pass URL.  i got the screenshot but now some issues in that.

1) Style does not include in this screenshot(i am not able to get image with style)
2) need to get only visible portion of the screen. now i got full page screenshot.

Thanks in advanced.

**Comment by mgrachev** [comment]
Hi there, @ronakpatel70

**Comment by mgrachev** [comment]
Hi, @ronakpatel70, thank you for your questions. Can you give me the URL for testing?

1). You can use `timeout` to wait for styles are loaded;
2). At the moment, it's impossible.
