### ISSUE TITLE
Some parts of the screenshot are missing

### ISSUE THREAD

**Issue by ashwin-elangovan** [mgrachev/gastly#9]
Hi,

While using Gastly to take screenshots in some websites, the screenshot is missing the header and footer. 

Can you please tell the solution?

![2](https://user-images.githubusercontent.com/35291686/43196330-2a77ebd2-9025-11e8-8d12-11cf7128341c.png)

**Comment by mgrachev** [comment]
@ashwin-elangovan Hi! Can you give me an example URL?

**Comment by ashwin-elangovan** [comment]
Hi,
The url is www.freshcaller.com

**Comment by mgrachev** [comment]
@ashwin-elangovan There is a problem with phantomjs - https://github.com/ariya/phantomjs/issues/12750.

Unfortunately, I can't fix this problem.
